export const setPrompt = ({ commit }) => commit('setPrompt');
export const setBaseInfo = ({ commit }) => commit('setBaseInfo');
export const setUserInfo = ({ commit }) => commit('setUserInfo');
export const setStudentId = ({ commit }) => commit('setStudentId');
export const setMerchantInfo = ({ commit }) => commit('setMerchantInfo');
export const setDailogShow = ({ commit }) => commit('setDailogShow');
export const setDailogObj = ({ commit }) => commit('setDailogObj');
export const setRecordUserName = ({ commit }) => commit('setRecordUserName');
export const addTabs = ({ commit }) => commit('addTabs');
export const replaceTab = ({ commit }) => commit('replaceTab');
export const deleteTabs = ({ commit }) => commit('deleteTabs');
export const activeIndex = ({ commit }) => commit('activeIndex');
export const saveDetailInfo = ({ commit }) => commit('saveDetailInfo');
export const setAuthData = ({ commit }) => commit('setAuthData');
export const setAuthArr=({commit})=>commit("setAuthArr");
export const setImgOrVideo=({commit})=>commit("setImgOrVideo");
export const setAuthTabs=({commit})=>commit("setAuthTabs");
export const setParamConfig=({commit})=>commit("setParamConfig");
export const setMemberInfo=({commit})=>commit("setMemberInfo");
export const setBaseRouter=({commit})=>commit("setBaseRouter");
export const setCancelToken=({commit})=>commit("setCancelToken");