export const isPrompt = state => state.isPrompt;
export const baseInfo = state => state.baseInfo;
export const userInfo = state => state.userInfo;
export const studentId = state => state.userInfo.studentId;
export const merchantInfo = state => state.merchantInfo;
export const dailogShow = state => state.setDailogShow;
export const recordUserName = state => state.recordUserName;
export const isCache = state => state.isCache;
export const exCache = state => state.exCache;
export const dailogObj = state => state.dailogObj;
export const authData = state => state.authData;
export const authArr =state => state.authArr;
export const imgOrVideo =state => state.imgOrVideo;
export const authTabs =state => state.authTabs;
export const paramConfig =state => state.paramConfig;
export const memberInfo =state => state.memberInfo;
export const baseRouter =state =>state.baseRouter;
export const cancelTokenArr = state => state.cancelTokenArr;