let JSON={
    "机构设置":{
        childMenu:{
            "机构首页":{
                address:"index", 
                display:true
            },
            "基本资料":{
                address:"basicInformation",
                display:true
            },
            "卡的类型":{
                address:"",
                display:true
            },
            "优惠类型":{
                address:"",
                display:true
            },
            "管理日志":{
                address:"",
                display:true
            },
            "参数设置":{
                address:"",
                display:true
            },
            "短信服务":{
                address:"",
                display:true
            },
            "用户管理":{
                address:"",
                display:true
            }
        },
        display:true
    },
    "人事管理":{
        childMenu:{
            "岗位级别设置":{
                address:"",
                display:true
            },
            "员工管理":{
                address:"",
                display:true
            },
            "员工考勤":{
                address:"",
                display:true
            }
        },
        display:true
    },
    "教案管理":{
        display:false
    },
    "班级管理":{
        display:false
    },
    "学员管理":{
        display:false
    },
    "体测管理":{
        display:false
    },
    "统计管理":{
        display:false
    },
    "财务管理":{
        display:false
    },
    "通知管理":{
        display:false
    },
    "销售管理":{
        display:false
    },
    "积分管理":{
        display:false
    },
    "商城管理":{
        display:false
    },
    "库存管理":{
        display:false
    },
    "互动管理":{
        display:false
    },
    "营销管理":{
        display:false
    }
};
export default JSON;